import type { Metadata } from "next";
import "./globals.css";
import App from "next/app";
import { AppProvider } from "./context/AppContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
